baseURL: /
title: Jaeger, a distributed tracing system
theme: jaeger-docs
languageCode: en-us
pygmentsCodeFences: true

params:
  navbar:
    links:
    - title: Docs
      url: /docs
    - title: Download
      url: /download
    - title: Community
      url: /community
    - title: Blog
      url: /blog
