baseURL: /
title: Jaeger, a distributed tracing system
theme: jaeger-docs
languageCode: en-us
pygmentsCodeFences: true

params:
  description: Jaeger, inspired by Dapper and OpenZipkin, is a distributed tracing system released as open source by Uber Technologies. It can be used for monitoring microservice-based architectures.
  navbar:
    links:
    - title: Docs
      url: /docs
    - title: Download
      url: /download
    - title: Community
      url: /community
    - title: Blog
      url: /blog
